rem sc stop "SQLBrowser"
rem sc stop "MSSQL$SQLEXPRESS"
rem sc stop "CF9Solr"
rem sc stop "ColdFusion 9 Search Server"
rem sc stop "ColdFusion 9 ODBC Server"
rem sc stop "ColdFusion 9 ODBC Agent"
rem sc stop "ColdFusion 9 .NET Service"
sc stop "ColdFusion 9 Application Server"
sc stop "Apache2"