sc start "Apache2"
sc start "ColdFusion 9 Application Server"
rem sc start "ColdFusion 9 .NET Service"
rem sc start "ColdFusion 9 ODBC Agent"
rem sc start "ColdFusion 9 ODBC Server"
rem sc start "ColdFusion 9 Search Server"
rem sc start "CF9Solr"
rem sc start "MSSQL$SQLEXPRESS"
rem sc start "SQLBrowser"